### ISSUE TITLE
Incorrect worktree path

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl-project-creator#16]
In `.git/modules/lvgl/config` the `worktree` entry should point to the LVGL. Now the path is incorrect.

**Comment by coevin** [comment]
@kisvegabor Could you provide an example of what the correct path should be.

**Comment by kisvegabor** [comment]
In case of the 
- Renesas board: `worktree = ../../../../src/lvgl`
- Eclipse board: `worktree = ../../../lvgl`

**Comment by kisvegabor** [comment]
Fixed in v1.1
